application: arunjit-gsgae
version: 1
runtime: java
threadsafe: true

system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties

listeners:
- net.arunjitsingh.gsgae.GuiceContextBootstrap

handlers:
- url: /_ah/spi/*
  servlet: com.google.api.server.spi.SystemServiceServlet
  name: SystemService

- url: /*
  filter: com.google.inject.servlet.GuiceFilter
  name: GuiceFilter

admin_console:
  pages:
  - name: Appstats
    url: /appstats
